# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClustersGenerator
                                 A QGIS plugin
 Genera Clusters aplicando modelos de aprendizaje no supervisados
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-10
        copyright            : (C) 2020 by Rober D
        email                : laquedasconelemail@123.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Rober D'
__date__ = '2020-10-10'
__copyright__ = '(C) 2020 by Rober D'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClustersGenerator class from file ClustersGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cluster_generator import ClustersGeneratorPlugin
    return ClustersGeneratorPlugin()
